#!/bin/bash

echo " -> Removing docker images"
docker rm -f percona

echo " -> Rebuilding the image from current directory"
docker build -t klevo/percona .

echo " -> Recreating data dir mount"
# boot2docker ssh "sudo rm -rf /home/docker/percona-data; mkdir -p /home/docker/percona-data"

echo " -> Run the new container"
docker run -d --name percona \
  -v /home/docker/percona-data:/var/lib/mysql \
  -e MYSQL_ROOT_PASSWORD=mypass \
  -p 3308:3306 \
  klevo/percona

echo " -> Done."
docker ps

docker exec -i -t percona /bin/bash