#!/bin/bash

echo " -> Removing docker images"
docker rm -vf db1 percona

echo " -> Rebuilding the image from current directory"
docker build -t klevo/percona .

# echo " -> Recreating data dir mount"
# boot2docker ssh "sudo rm -rf /home/docker/percona-data; mkdir -p /home/docker/percona-data"

echo " -> Run the slave container"

docker run -d --name db1 \
  -e MYSQL_ROOT_PASSWORD=mypass \
  --hostname db1 \
  klevo/percona

echo " -> Done."
docker ps

docker exec -i -t db1 bash